name: edu_sync
description: A collaborative PDF question organizer app for JEE aspirants.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  file_picker: ^8.1.4
  syncfusion_flutter_pdfviewer: ^33.2.13
  http: ^1.2.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_svg: ^2.3.0
  syncfusion_flutter_pdf: ^33.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4



flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/logo_full_bleed.svg
    - assets/images/branded_page_bg.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: 'assets/images/app_icon.png'
  web:
    generate: true
    image_path: 'assets/images/app_icon.png'
    background_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/images/app_icon.png'
